
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 389;
const int acc_off_y = 82;
const int acc_off_z = 2083;
const float acc_scale_x = 16294.721810;
const float acc_scale_y = 16336.774940;
const float acc_scale_z = 16621.171104;

const int magn_off_x = -55;
const int magn_off_y = -127;
const int magn_off_z = -20;
const float magn_scale_x = 522.100275;
const float magn_scale_y = 490.744465;
const float magn_scale_z = 466.478712;
