
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 273;
const int acc_off_y = 60;
const int acc_off_z = 2297;
const float acc_scale_x = 16292.892636;
const float acc_scale_y = 16452.125894;
const float acc_scale_z = 16718.925861;

const int magn_off_x = -87;
const int magn_off_y = -66;
const int magn_off_z = 147;
const float magn_scale_x = 561.265766;
const float magn_scale_y = 515.504362;
const float magn_scale_z = 471.026031;
