
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 204;
const int acc_off_y = -11;
const int acc_off_z = 2033;
const float acc_scale_x = 16310.204894;
const float acc_scale_y = 16369.693317;
const float acc_scale_z = 16672.439290;

const int magn_off_x = -49;
const int magn_off_y = -70;
const int magn_off_z = 23;
const float magn_scale_x = 535.920637;
const float magn_scale_y = 499.238496;
const float magn_scale_z = 453.973802;
