
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 43;
const int acc_off_y = -71;
const int acc_off_z = 1414;
const float acc_scale_x = 16466.404159;
const float acc_scale_y = 16502.275454;
const float acc_scale_z = 16711.110165;

const int magn_off_x = -1;
const int magn_off_y = -67;
const int magn_off_z = -26;
const float magn_scale_x = 524.399730;
const float magn_scale_y = 491.219696;
const float magn_scale_z = 473.890738;
