
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 322;
const int acc_off_y = 216;
const int acc_off_z = 1596;
const float acc_scale_x = 16467.400206;
const float acc_scale_y = 16412.632323;
const float acc_scale_z = 16834.362970;

const int magn_off_x = 0;
const int magn_off_y = -53;
const int magn_off_z = -8;
const float magn_scale_x = 548.914102;
const float magn_scale_y = 520.401566;
const float magn_scale_z = 491.259836;
