
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 89;
const int acc_off_y = 32;
const int acc_off_z = 2708;
const float acc_scale_x = 16386.652279;
const float acc_scale_y = 16351.250348;
const float acc_scale_z = 16579.212920;

const int magn_off_x = 24;
const int magn_off_y = -34;
const int magn_off_z = -1;
const float magn_scale_x = 541.252165;
const float magn_scale_y = 509.329748;
const float magn_scale_z = 456.377591;
