
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 267;
const int acc_off_y = 2;
const int acc_off_z = 1607;
const float acc_scale_x = 16494.843304;
const float acc_scale_y = 16448.809782;
const float acc_scale_z = 16775.003024;

const int magn_off_x = 32;
const int magn_off_y = -101;
const int magn_off_z = -21;
const float magn_scale_x = 545.371699;
const float magn_scale_y = 514.181197;
const float magn_scale_z = 475.319744;
