
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 240;
const int acc_off_y = -103;
const int acc_off_z = -1040;
const float acc_scale_x = 16527.832968;
const float acc_scale_y = 16362.661637;
const float acc_scale_z = 16683.945280;

const int magn_off_x = 582;
const int magn_off_y = -93;
const int magn_off_z = -173;
const float magn_scale_x = 545.169762;
const float magn_scale_y = 537.496807;
const float magn_scale_z = 522.795161;
