
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 261;
const int acc_off_y = 156;
const int acc_off_z = 491;
const float acc_scale_x = 16386.272503;
const float acc_scale_y = 16494.930885;
const float acc_scale_z = 16772.044958;

const int magn_off_x = -100;
const int magn_off_y = -137;
const int magn_off_z = -52;
const float magn_scale_x = 567.008521;
const float magn_scale_y = 528.510663;
const float magn_scale_z = 477.477617;
